name: exhibition_hub
description: A new Flutter project for managing exhibitions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  uuid: ^4.2.1
  # State Management
  # provider: ^6.1.1
  # UI Components
  # flutter_svg: ^2.0.9
  # cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  # Navigation
  # go_router: ^13.1.0
  # Authentication & Storage
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  # firebase_messaging: ^14.6.5
  shared_preferences: ^2.2.0
  # Maps & Location
  google_maps_flutter: ^2.2.5
  geolocator: ^10.0.0
  # Payment (placeholder for future implementation)
  # stripe_payment: ^1.1.4
  # Utilities
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  permission_handler: ^10.3.0
  # Analytics
  firebase_analytics: ^10.4.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  mockito: ^5.4.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/ 